/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiDownloadChar123eventIdChar125DotzipRouteImport } from './routes/api/download.{$eventId}[.]zip'
import { Route as ApiQrChar123eventIdChar125DotpngRouteImport } from './routes/api/qr.{$eventId}[.]png'
import { Route as ApiUploadsPresignRouteImport } from './routes/api/uploads.presign'
import { Route as EEventSlugIndexRouteImport } from './routes/e/$eventSlug/index'
import { Route as EEventSlugThankYouRouteImport } from './routes/e/$eventSlug/thank-you'
import { Route as AuthedAdminPengantinIdRouteImport } from './routes/_authed/admin/pengantin.$id'
import { Route as AuthedAdminPengantinNewRouteImport } from './routes/_authed/admin/pengantin.new'
import { Route as AuthedDashboardEventsNewRouteImport } from './routes/_authed/dashboard/events.new'
import { Route as AuthedAdminEventsEventIdQrRouteImport } from './routes/_authed/admin/events.$eventId.qr'
import { Route as AuthedDashboardEventsEventIdIndexRouteImport } from './routes/_authed/dashboard/events.$eventId/index'
import { Route as AuthedDashboardEventsEventIdFramesRouteImport } from './routes/_authed/dashboard/events.$eventId/frames'
import { Route as AuthedDashboardEventsEventIdSettingsRouteImport } from './routes/_authed/dashboard/events.$eventId/settings'
import { Route as AuthedDashboardEventsEventIdSubmissionsRouteImport } from './routes/_authed/dashboard/events.$eventId/submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadChar123eventIdChar125DotzipRoute =
  ApiDownloadChar123eventIdChar125DotzipRouteImport.update({
    id: '/api/download/{$eventId}.zip',
    path: '/api/download/{$eventId}.zip',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQrChar123eventIdChar125DotpngRoute =
  ApiQrChar123eventIdChar125DotpngRouteImport.update({
    id: '/api/qr/{$eventId}.png',
    path: '/api/qr/{$eventId}.png',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadsPresignRoute = ApiUploadsPresignRouteImport.update({
  id: '/api/uploads/presign',
  path: '/api/uploads/presign',
  getParentRoute: () => rootRouteImport,
} as any)
const EEventSlugIndexRoute = EEventSlugIndexRouteImport.update({
  id: '/e/$eventSlug/',
  path: '/e/$eventSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const EEventSlugThankYouRoute = EEventSlugThankYouRouteImport.update({
  id: '/e/$eventSlug/thank-you',
  path: '/e/$eventSlug/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminPengantinIdRoute = AuthedAdminPengantinIdRouteImport.update({
  id: '/pengantin/$id',
  path: '/pengantin/$id',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminPengantinNewRoute = AuthedAdminPengantinNewRouteImport.update({
  id: '/pengantin/new',
  path: '/pengantin/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedDashboardEventsNewRoute =
  AuthedDashboardEventsNewRouteImport.update({
    id: '/events/new',
    path: '/events/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedAdminEventsEventIdQrRoute =
  AuthedAdminEventsEventIdQrRouteImport.update({
    id: '/events/$eventId/qr',
    path: '/events/$eventId/qr',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedDashboardEventsEventIdIndexRoute =
  AuthedDashboardEventsEventIdIndexRouteImport.update({
    id: '/events/$eventId/',
    path: '/events/$eventId/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardEventsEventIdFramesRoute =
  AuthedDashboardEventsEventIdFramesRouteImport.update({
    id: '/events/$eventId/frames',
    path: '/events/$eventId/frames',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardEventsEventIdSettingsRoute =
  AuthedDashboardEventsEventIdSettingsRouteImport.update({
    id: '/events/$eventId/settings',
    path: '/events/$eventId/settings',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardEventsEventIdSubmissionsRoute =
  AuthedDashboardEventsEventIdSubmissionsRouteImport.update({
    id: '/events/$eventId/submissions',
    path: '/events/$eventId/submissions',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/{$eventId}.zip': typeof ApiDownloadChar123eventIdChar125DotzipRoute
  '/api/qr/{$eventId}.png': typeof ApiQrChar123eventIdChar125DotpngRoute
  '/api/uploads/presign': typeof ApiUploadsPresignRoute
  '/e/$eventSlug/thank-you': typeof EEventSlugThankYouRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/e/$eventSlug/': typeof EEventSlugIndexRoute
  '/admin/pengantin/$id': typeof AuthedAdminPengantinIdRoute
  '/admin/pengantin/new': typeof AuthedAdminPengantinNewRoute
  '/dashboard/events/new': typeof AuthedDashboardEventsNewRoute
  '/admin/events/$eventId/qr': typeof AuthedAdminEventsEventIdQrRoute
  '/dashboard/events/$eventId/frames': typeof AuthedDashboardEventsEventIdFramesRoute
  '/dashboard/events/$eventId/settings': typeof AuthedDashboardEventsEventIdSettingsRoute
  '/dashboard/events/$eventId/submissions': typeof AuthedDashboardEventsEventIdSubmissionsRoute
  '/dashboard/events/$eventId/': typeof AuthedDashboardEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/{$eventId}.zip': typeof ApiDownloadChar123eventIdChar125DotzipRoute
  '/api/qr/{$eventId}.png': typeof ApiQrChar123eventIdChar125DotpngRoute
  '/api/uploads/presign': typeof ApiUploadsPresignRoute
  '/e/$eventSlug/thank-you': typeof EEventSlugThankYouRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/e/$eventSlug': typeof EEventSlugIndexRoute
  '/admin/pengantin/$id': typeof AuthedAdminPengantinIdRoute
  '/admin/pengantin/new': typeof AuthedAdminPengantinNewRoute
  '/dashboard/events/new': typeof AuthedDashboardEventsNewRoute
  '/admin/events/$eventId/qr': typeof AuthedAdminEventsEventIdQrRoute
  '/dashboard/events/$eventId/frames': typeof AuthedDashboardEventsEventIdFramesRoute
  '/dashboard/events/$eventId/settings': typeof AuthedDashboardEventsEventIdSettingsRoute
  '/dashboard/events/$eventId/submissions': typeof AuthedDashboardEventsEventIdSubmissionsRoute
  '/dashboard/events/$eventId': typeof AuthedDashboardEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/{$eventId}.zip': typeof ApiDownloadChar123eventIdChar125DotzipRoute
  '/api/qr/{$eventId}.png': typeof ApiQrChar123eventIdChar125DotpngRoute
  '/api/uploads/presign': typeof ApiUploadsPresignRoute
  '/e/$eventSlug/thank-you': typeof EEventSlugThankYouRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/e/$eventSlug/': typeof EEventSlugIndexRoute
  '/_authed/admin/pengantin/$id': typeof AuthedAdminPengantinIdRoute
  '/_authed/admin/pengantin/new': typeof AuthedAdminPengantinNewRoute
  '/_authed/dashboard/events/new': typeof AuthedDashboardEventsNewRoute
  '/_authed/admin/events/$eventId/qr': typeof AuthedAdminEventsEventIdQrRoute
  '/_authed/dashboard/events/$eventId/frames': typeof AuthedDashboardEventsEventIdFramesRoute
  '/_authed/dashboard/events/$eventId/settings': typeof AuthedDashboardEventsEventIdSettingsRoute
  '/_authed/dashboard/events/$eventId/submissions': typeof AuthedDashboardEventsEventIdSubmissionsRoute
  '/_authed/dashboard/events/$eventId/': typeof AuthedDashboardEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/download/{$eventId}.zip'
    | '/api/qr/{$eventId}.png'
    | '/api/uploads/presign'
    | '/e/$eventSlug/thank-you'
    | '/admin/'
    | '/dashboard/'
    | '/e/$eventSlug/'
    | '/admin/pengantin/$id'
    | '/admin/pengantin/new'
    | '/dashboard/events/new'
    | '/admin/events/$eventId/qr'
    | '/dashboard/events/$eventId/frames'
    | '/dashboard/events/$eventId/settings'
    | '/dashboard/events/$eventId/submissions'
    | '/dashboard/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/api/download/{$eventId}.zip'
    | '/api/qr/{$eventId}.png'
    | '/api/uploads/presign'
    | '/e/$eventSlug/thank-you'
    | '/admin'
    | '/dashboard'
    | '/e/$eventSlug'
    | '/admin/pengantin/$id'
    | '/admin/pengantin/new'
    | '/dashboard/events/new'
    | '/admin/events/$eventId/qr'
    | '/dashboard/events/$eventId/frames'
    | '/dashboard/events/$eventId/settings'
    | '/dashboard/events/$eventId/submissions'
    | '/dashboard/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/api/auth/$'
    | '/api/download/{$eventId}.zip'
    | '/api/qr/{$eventId}.png'
    | '/api/uploads/presign'
    | '/e/$eventSlug/thank-you'
    | '/_authed/admin/'
    | '/_authed/dashboard/'
    | '/e/$eventSlug/'
    | '/_authed/admin/pengantin/$id'
    | '/_authed/admin/pengantin/new'
    | '/_authed/dashboard/events/new'
    | '/_authed/admin/events/$eventId/qr'
    | '/_authed/dashboard/events/$eventId/frames'
    | '/_authed/dashboard/events/$eventId/settings'
    | '/_authed/dashboard/events/$eventId/submissions'
    | '/_authed/dashboard/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadChar123eventIdChar125DotzipRoute: typeof ApiDownloadChar123eventIdChar125DotzipRoute
  ApiQrChar123eventIdChar125DotpngRoute: typeof ApiQrChar123eventIdChar125DotpngRoute
  ApiUploadsPresignRoute: typeof ApiUploadsPresignRoute
  EEventSlugThankYouRoute: typeof EEventSlugThankYouRoute
  EEventSlugIndexRoute: typeof EEventSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/{$eventId}.zip': {
      id: '/api/download/{$eventId}.zip'
      path: '/api/download/{$eventId}.zip'
      fullPath: '/api/download/{$eventId}.zip'
      preLoaderRoute: typeof ApiDownloadChar123eventIdChar125DotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qr/{$eventId}.png': {
      id: '/api/qr/{$eventId}.png'
      path: '/api/qr/{$eventId}.png'
      fullPath: '/api/qr/{$eventId}.png'
      preLoaderRoute: typeof ApiQrChar123eventIdChar125DotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/presign': {
      id: '/api/uploads/presign'
      path: '/api/uploads/presign'
      fullPath: '/api/uploads/presign'
      preLoaderRoute: typeof ApiUploadsPresignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$eventSlug/': {
      id: '/e/$eventSlug/'
      path: '/e/$eventSlug'
      fullPath: '/e/$eventSlug/'
      preLoaderRoute: typeof EEventSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$eventSlug/thank-you': {
      id: '/e/$eventSlug/thank-you'
      path: '/e/$eventSlug/thank-you'
      fullPath: '/e/$eventSlug/thank-you'
      preLoaderRoute: typeof EEventSlugThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/pengantin/$id': {
      id: '/_authed/admin/pengantin/$id'
      path: '/pengantin/$id'
      fullPath: '/admin/pengantin/$id'
      preLoaderRoute: typeof AuthedAdminPengantinIdRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/pengantin/new': {
      id: '/_authed/admin/pengantin/new'
      path: '/pengantin/new'
      fullPath: '/admin/pengantin/new'
      preLoaderRoute: typeof AuthedAdminPengantinNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/dashboard/events/new': {
      id: '/_authed/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof AuthedDashboardEventsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/admin/events/$eventId/qr': {
      id: '/_authed/admin/events/$eventId/qr'
      path: '/events/$eventId/qr'
      fullPath: '/admin/events/$eventId/qr'
      preLoaderRoute: typeof AuthedAdminEventsEventIdQrRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/dashboard/events/$eventId/': {
      id: '/_authed/dashboard/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/dashboard/events/$eventId/'
      preLoaderRoute: typeof AuthedDashboardEventsEventIdIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/events/$eventId/frames': {
      id: '/_authed/dashboard/events/$eventId/frames'
      path: '/events/$eventId/frames'
      fullPath: '/dashboard/events/$eventId/frames'
      preLoaderRoute: typeof AuthedDashboardEventsEventIdFramesRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/events/$eventId/settings': {
      id: '/_authed/dashboard/events/$eventId/settings'
      path: '/events/$eventId/settings'
      fullPath: '/dashboard/events/$eventId/settings'
      preLoaderRoute: typeof AuthedDashboardEventsEventIdSettingsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/dashboard/events/$eventId/submissions': {
      id: '/_authed/dashboard/events/$eventId/submissions'
      path: '/events/$eventId/submissions'
      fullPath: '/dashboard/events/$eventId/submissions'
      preLoaderRoute: typeof AuthedDashboardEventsEventIdSubmissionsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminPengantinIdRoute: typeof AuthedAdminPengantinIdRoute
  AuthedAdminPengantinNewRoute: typeof AuthedAdminPengantinNewRoute
  AuthedAdminEventsEventIdQrRoute: typeof AuthedAdminEventsEventIdQrRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminPengantinIdRoute: AuthedAdminPengantinIdRoute,
  AuthedAdminPengantinNewRoute: AuthedAdminPengantinNewRoute,
  AuthedAdminEventsEventIdQrRoute: AuthedAdminEventsEventIdQrRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedDashboardRouteChildren {
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardEventsNewRoute: typeof AuthedDashboardEventsNewRoute
  AuthedDashboardEventsEventIdFramesRoute: typeof AuthedDashboardEventsEventIdFramesRoute
  AuthedDashboardEventsEventIdSettingsRoute: typeof AuthedDashboardEventsEventIdSettingsRoute
  AuthedDashboardEventsEventIdSubmissionsRoute: typeof AuthedDashboardEventsEventIdSubmissionsRoute
  AuthedDashboardEventsEventIdIndexRoute: typeof AuthedDashboardEventsEventIdIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardEventsNewRoute: AuthedDashboardEventsNewRoute,
  AuthedDashboardEventsEventIdFramesRoute:
    AuthedDashboardEventsEventIdFramesRoute,
  AuthedDashboardEventsEventIdSettingsRoute:
    AuthedDashboardEventsEventIdSettingsRoute,
  AuthedDashboardEventsEventIdSubmissionsRoute:
    AuthedDashboardEventsEventIdSubmissionsRoute,
  AuthedDashboardEventsEventIdIndexRoute:
    AuthedDashboardEventsEventIdIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadChar123eventIdChar125DotzipRoute:
    ApiDownloadChar123eventIdChar125DotzipRoute,
  ApiQrChar123eventIdChar125DotpngRoute: ApiQrChar123eventIdChar125DotpngRoute,
  ApiUploadsPresignRoute: ApiUploadsPresignRoute,
  EEventSlugThankYouRoute: EEventSlugThankYouRoute,
  EEventSlugIndexRoute: EEventSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
